tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#9cf0ff",
        "on-primary-fixed-variant": "#3c4d00",
        "surface-variant": "#353534",
        "on-secondary-container": "#00616d",
        secondary: "#bdf4ff",
        primary: "#ffffff",
        "on-tertiary-fixed": "#0b1d29",
        "on-primary": "#283500",
        surface: "#131313",
        "on-tertiary": "#21323e",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed-variant": "#374956",
        "tertiary-container": "#d2e5f5",
        background: "#131313",
        "on-secondary-fixed": "#001f24",
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#444933",
        "primary-fixed-dim": "#abd600",
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#556d00",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#201f1f",
        error: "#ffb4ab",
        "on-primary-fixed": "#161e00",
        "tertiary-fixed": "#d2e5f5",
        "surface-tint": "#abd600",
        "secondary-fixed-dim": "#00daf3",
        tertiary: "#ffffff",
        "on-background": "#e5e2e1",
        outline: "#8e9379",
        "tertiary-fixed-dim": "#b6c9d8",
        "inverse-primary": "#506600",
        "primary-container": "#c3f400",
        "on-surface-variant": "#c4c9ac",
        "on-secondary-fixed-variant": "#004f58",
        "surface-container-highest": "#353534",
        "on-secondary": "#00363d",
        "primary-fixed": "#c3f400",
        "on-tertiary-container": "#556774",
        "surface-bright": "#393939",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "secondary-container": "#00e3fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        gutter: "16px",
        "margin-mobile": "20px",
        md: "24px",
        base: "8px",
        xs: "4px",
        "margin-desktop": "120px",
        lg: "48px",
        xl: "64px",
      },
      fontFamily: {
        "data-mono": ["Sora"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Sora"],
        "body-md": ["Hanken Grotesk"],
        "display-lg": ["Sora"],
        "headline-md": ["Sora"],
        "label-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Sora"],
      },
      fontSize: {
        "data-mono": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "34px", fontWeight: "700" },
        ],
      },
    },
  },
};
